version: 1
review:
  path_includes:
    - "app/"
    - "routes/"
    - "database/"
    - "resources/views/"
    - "resources/js/"
    - "resources/css/"
  path_excludes:
    - "vendor/"
    - "node_modules/"
    - "storage/"
    - "bootstrap/cache/"
    - "public/"
  languages:
    - php
  settings:
    framework: laravel
    database: postgres
    style_checks: true
    security_checks: true
    timeout: 600
  comments:
    explain_code: true
    suggest_best_practices: true
    detect_dead_code: true
    detect_security_issues: true
    summarize_pr: true
  focus_areas:
    - "Laravel model conventions"
    - "Eloquent relationships"
    - "Performance optimizations"
    - "Security best practices"
