<?php

return [
    'nqn' => [
        ['city_name' => 'Alumine'],
        ['city_name' => 'Andacollo'],
        ['city_name' => 'Arroyito'],
        ['city_name' => 'Caviahue'],
        ['city_name' => 'Centenario'],
        ['city_name' => 'Chos Malal'],
        ['city_name' => 'Copahue'],
        ['city_name' => 'Cutral Co'],
        ['city_name' => 'El Cholar'],
        ['city_name' => 'El Huecu'],
        ['city_name' => 'Huinganco'],
        ['city_name' => 'Junin de los Andes'],
        ['city_name' => 'Las Lajas'],
        ['city_name' => 'Las Ovejas'],
        ['city_name' => 'Loncopue'],
        ['city_name' => 'Manzano Amargo'],
        ['city_name' => 'Moquehue'],
        ['city_name' => 'Neuquen Capital'],
        ['city_name' => 'Picun Leufu'],
        ['city_name' => 'Piedra del Aguila'],
        ['city_name' => 'Plaza Huincul'],
        ['city_name' => 'Plottier'],
        ['city_name' => 'Primeros Pinos'],
        ['city_name' => 'Pulmari'],
        ['city_name' => 'Rincón de los Sauces'],
        ['city_name' => 'San Martin de los Andes'],
        ['city_name' => 'Tricao Malal'],
        ['city_name' => 'Varvarco'],
        ['city_name' => 'Villa El Chocon'],
        ['city_name' => 'Villa La Angostura'],
        ['city_name' => 'Villa Lago Meliquina'],
        ['city_name' => 'Villa Pehuenia'],
        ['city_name' => 'Villa Traful'],
        ['city_name' => 'Zapala'],
    ],

    'rno' => [
        ['city_name' => 'Allen'],
        ['city_name' => 'Bariloche'],
        ['city_name' => 'Catriel'],
        ['city_name' => 'Choele Choel'],
        ['city_name' => 'Cinco Saltos'],
        ['city_name' => 'Cipolletti'],
        ['city_name' => 'Dina Huapi'],
        ['city_name' => 'El Bolson'],
        ['city_name' => 'El Manso'],
        ['city_name' => 'General Conesa'],
        ['city_name' => 'General Roca'],
        ['city_name' => 'Ingeniero Jacobacci'],
        ['city_name' => 'Las Grutas'],
        ['city_name' => 'Los Menucos'],
        ['city_name' => 'Ministro Ramos Mexia'],
        ['city_name' => 'Playas Doradas'],
        ['city_name' => 'Rio Colorado'],
        ['city_name' => 'San Antonio Este'],
        ['city_name' => 'San Antonio Oeste'],
        ['city_name' => 'Sierra Colorada'],
        ['city_name' => 'Sierra Grande'],
        ['city_name' => 'Valcheta'],
        ['city_name' => 'Viedma'],
        ['city_name' => 'Villa El Condor'],
        ['city_name' => 'Villa Lago Gutiérrez'],
        ['city_name' => 'Villa Lago Mascardi'],
        ['city_name' => 'Villa Regina'],
    ],
];
