<?php

declare(strict_types=1);

return [
    'company' => 'empresa',
    'cuit' => 'cuit',
    'sucursal' => 'sucursal',
    'user' => 'usuario',
    'name' => 'nombre',
    'apellido' => 'apellido',
    'telefono' => 'teléfono',
    'correo' => 'correo',
    'web' => 'web',
    'direccion' => 'dirección',
    'cp' => 'c.p',
    'departamento' => 'departamento',
    'codigo' => 'código',
    'contacto' => 'contacto',
    'provincia' => 'provincia',
    'campo_obligado' => 'campo obligatorio',
    'person_contact' => 'persona de contacto',
    'person_email' => 'correo de contacto',
    'siglas' => 'siglas',
    'tipo' => 'tipo',
    'dni' => 'dni',
    'status' => 'estatus',
    'matricula' => 'matricula',
    'especialist' => 'especialidad',
    'titulo' => 'titulo',
    'codigomedico' => 'núm matricula',
    'medical' => 'especialista',
    'insurance' => 'obra social',
    'role' => 'rol',
    'descripcion' => 'descripción',
    'action' => 'acción',
    'acceso' => 'acceso',
    'documtype' => 'documento',
    'documtnume' => 'número',
    'gender' => 'genero',
    'datebirth' => 'fecha de nacimiento',
    'maritalstatus' => 'estado civil',
    'occupation' => 'ocupación',
    'nacionalidad' => 'nacionalidad',
];
