<?php

declare(strict_types=1);

return [
    'company' => 'empresa',
    'cuit' => 'cuit',
    'sucursal' => 'sucursal',
    'user' => 'usuario',
    'name' => 'nombre',
    'apellido' => 'apellido',
    'telefono' => 'teléfono',
    'correo' => 'correo',
    'web' => 'web',
    'direccion' => 'dirección',
    'cp' => 'cp',
    'departamento' => 'departamento',
    'codigo' => 'código',
    'contacto' => 'contacto',
    'provincia' => 'provincia',
    'campo_obligado' => 'campo obligatorio',
    'person_contact' => 'persona de contacto',
    'person_email' => 'correo de contacto',
    'siglas' => 'siglas',
    'tipo' => 'tipo',
    'dni' => 'dni',
    'status' => 'estatus',
    'matricula' => 'matricula',
    'especialist' => 'especialidad',
    'titulo' => 'titulo',
    'codigomedico' => 'núm matricula',
    'medical' => 'especialista',
    'insurance' => 'obra social',
    'role' => 'rol',
    'descripcion' => 'descripción',
    'condicion' => 'condiciones',
    'action' => 'acción',
    'acceso' => 'acceso',
    'documtype' => 'documento',
    'documtnume' => 'número',
    'gender' => 'genero',
    'datebirth' => 'fecha de nacimiento',
    'fechainicio' => 'fecha inicio',
    'fechafin' => 'fecha fin',
    'maritalstatus' => 'estado civil',
    'occupation' => 'ocupación',
    'nacionalidad' => 'nacionalidad',
    'day_of_week' => 'horario',
    'service' => 'servicio',
    'prestador' => 'prestador',
    'category' => 'categoria',
    'preparacion' => 'preparación',
    'pricipal' => 'servicio principal',
    'instrucciones' => 'instrucciones',
    'price' => 'precio',
    'duration' => 'duración',
    'orden' => 'ordenes',
];
